import { Scheme } from './types';

export const SCHEMES: Scheme[] = [
  {
    id: 'pm-kisan',
    mitraId: 'MITRA-STATIC-PMKISAN-001',
    name: 'PM Kisan Samman Nidhi',
    hindiName: 'PM किसान सम्मान निधि',
    description: 'Income support of ₹6,000 per year in three equal installments to all landholding farmer families.',
    hindiDescription: 'सभी भूमिधारक किसान परिवारों को तीन समान किस्तों में ₹6,000 प्रति वर्ष की आय सहायता।',
    eligibility: ['Small and marginal farmers', 'Land ownership proof required'],
    benefits: ['₹2,000 every 4 months', 'Direct Benefit Transfer (DBT)'],
    documents: ['Aadhar Card', 'Land Records', 'Bank Account Details'],
    category: 'Agriculture',
    community: 'Normal',
    officialUrl: 'https://pmkisan.gov.in/',
    image: 'https://images.unsplash.com/photo-1592982537447-7440770cbfc9?q=80&w=800&auto=format&fit=crop',
    aiVersion: 'Mitra Core v1.0',
    deadline: Date.now() + 5 * 24 * 60 * 60 * 1000
  },
  {
    id: 'ayushman-bharat',
    mitraId: 'MITRA-STATIC-PMJAY-002',
    name: 'Ayushman Bharat (PM-JAY)',
    hindiName: 'आयुष्मान भारत (PM-JAY)',
    description: 'Health cover of ₹5 lakh per family per year for secondary and tertiary care hospitalization.',
    hindiDescription: 'द्वितीयक और तृतीयक देखभाल अस्पताल में भर्ती के लिए प्रति परिवार प्रति वर्ष ₹5 लाख का स्वास्थ्य कवर।',
    eligibility: ['Low-income families', 'List based on SECC 2011 data'],
    benefits: ['Cashless treatment', 'Covers pre and post hospitalization'],
    documents: ['Aadhar Card', 'Ration Card', 'PM Letter (if available)'],
    category: 'Health',
    community: 'Normal',
    officialUrl: 'https://pmjay.gov.in/',
    image: 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?q=80&w=800&auto=format&fit=crop',
    aiVersion: 'Mitra Core v1.0',
    deadline: Date.now() + 8 * 24 * 60 * 60 * 1000
  },
  {
    id: 'ration-card',
    mitraId: 'MITRA-STATIC-NFSA-003',
    name: 'Ration Card (NFSA)',
    hindiName: 'राशन कार्ड (राष्ट्रीय खाद्य सुरक्षा अधिनियम)',
    description: 'Subsidized food grains through the Public Distribution System (PDS).',
    hindiDescription: 'सार्वजनिक वितरण प्रणाली (PDS) के माध्यम से रियायती खाद्यान्न।',
    eligibility: ['Citizens below poverty line', 'Depends on state-specific criteria'],
    benefits: ['Rice, Wheat at low costs', 'Identity proof for other schemes'],
    documents: ['Aadhar Card', 'Address Proof', 'Income Certificate'],
    category: 'Social',
    community: 'Normal',
    officialUrl: 'https://nfsa.gov.in/',
    image: 'https://images.unsplash.com/photo-1593113598332-cd288d649433?q=80&w=800&auto=format&fit=crop',
    aiVersion: 'Mitra Core v1.0'
  },
  {
    id: 'kanya-sumangala',
    mitraId: 'MITRA-STATIC-KANYA-004',
    name: 'Mukhya Mantri Kanya Sumangala Yojana',
    hindiName: 'मुख्यमंत्री कन्या सुमंगला योजना',
    description: 'Financial assistance to girl children in Uttar Pradesh for education and health.',
    hindiDescription: 'उत्तर प्रदेश में बालिकाओं को शिक्षा और स्वास्थ्य के लिए वित्तीय सहायता।',
    eligibility: ['Permanent resident of Uttar Pradesh', 'Family income below 3 lakh'],
    benefits: ['₹15,000 in total installments', 'Educational support'],
    documents: ['Aadhar Card', 'Birth Certificate', 'Income Certificate'],
    category: 'Social',
    community: 'Normal',
    state: 'Uttar Pradesh',
    officialUrl: 'https://mksy.up.gov.in/',
    image: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?q=80&w=800&auto=format&fit=crop',
    aiVersion: 'Mitra Core v1.0',
    deadline: Date.now() + 2 * 24 * 60 * 60 * 1000, 
    lastUpdate: Date.now() - 1 * 24 * 60 * 60 * 1000 
  },
  {
    id: 'bihar-student-credit-card',
    mitraId: 'MITRA-STATIC-BIHAR-005',
    name: 'Bihar Student Credit Card Scheme',
    hindiName: 'बिहार स्टूडेंट क्रेडिट कार्ड योजना',
    description: 'Education loan of up to ₹4 lakh for students of Bihar for higher education.',
    hindiDescription: 'उच्च शिक्षा के लिए बिहार के छात्रों के लिए ₹4 लाख तक का शिक्षा ऋण।',
    eligibility: ['Resident of Bihar', 'Passed 12th standard', 'Age between 18 and 28 years'],
    benefits: ['Low interest loan', 'Covers tuition and living expenses', 'Flexible monthly allowance up to ₹10,000'],
    documents: ['Aadhar Card', 'Marksheets', 'Valid ID', 'Income Certificate'],
    category: 'Education',
    community: 'Student',
    state: 'Bihar',
    officialUrl: 'https://www.7nishchay-yuvaupmission.bihar.gov.in/',
    image: 'https://images.unsplash.com/photo-1546410531-bb4caa6b424d?q=80&w=800&auto=format&fit=crop',
    aiVersion: 'Mitra Core v1.0',
    deadline: Date.now() + 60 * 24 * 60 * 60 * 1000, // active
    lastUpdate: Date.now() - 5000,
    ageLimit: 'Age between 18 and 28 years',
    gpaRequirement: 'Passed 12th standard with minimum 50% aggregate marks',
    applicationMode: 'Online',
    monthlyAmount: '₹10,000 per month (living stipend loan portion)',
    nextCycleExpected: 'Expected Opens April 2027',
    lastDeadline: '31 Aug 2026',
    opening: '1 Apr 2026'
  },
  {
    id: 'sukanya-samriddhi',
    mitraId: 'MITRA-STATIC-SUKANYA-006',
    name: 'Sukanya Samriddhi Yojana',
    hindiName: 'सुकन्या समृद्धि योजना',
    description: 'A small deposit scheme for the girl child to meet her education and marriage expenses.',
    hindiDescription: 'बालिका की शिक्षा और विवाह के खर्चों को पूरा करने के लिए एक छोटी बचत योजना।',
    eligibility: ['Parents of girl child below 10 years', 'Indian citizen'],
    benefits: ['High interest rate', 'Tax benefits under 80C'],
    documents: ['Birth Certificate', 'Identity Proof', 'Address Proof'],
    category: 'Finance',
    community: 'Normal',
    officialUrl: 'https://www.nsiindia.gov.in/',
    image: 'https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?q=80&w=800&auto=format&fit=crop',
    aiVersion: 'Mitra Core v1.0'
  },
  {
    id: 'pm-surya-ghar',
    mitraId: 'MITRA-STATIC-SURYA-007',
    name: 'PM Surya Ghar: Muft Bijli Yojana',
    hindiName: 'पीएम-सूर्य घर: मुफ्त बिजली योजना',
    description: 'Free electricity scheme for households by installing rooftop solar panels.',
    hindiDescription: 'छत पर सौर पैनल लगाकर घरों के लिए मुफ्त बिजली योजना।',
    eligibility: ['Owns a house', 'Indian citizen'],
    benefits: ['Up to 300 units free electricity', 'Subsidy on solar panels'],
    documents: ['Electricity Bill', 'Property Documents', 'Aadhar Card'],
    category: 'Finance',
    community: 'Normal',
    officialUrl: 'https://pmsuryaghar.gov.in/',
    image: 'https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?q=80&w=800&auto=format&fit=crop',
    aiVersion: 'Mitra Core v1.0',
    deadline: Date.now() + 3 * 24 * 60 * 60 * 1000
  },
  {
    id: 'ujjwala-yojana',
    mitraId: 'MITRA-STATIC-UJJWALA-008',
    name: 'PM Ujjwala Yojana',
    hindiName: 'पीएम उज्ज्वला योजना',
    description: 'Free LPG connections to women from below poverty line (BPL) households.',
    hindiDescription: 'गरीबी रेखा से नीचे (BPL) परिवारों की महिलाओं को मुफ्त LPG कनेक्शन।',
    eligibility: ['Woman above 18 years', 'BPL family', 'No existing LPG connection'],
    benefits: ['Free LPG connection', 'Cash assistance for stove and first refill'],
    documents: ['Aadhar Card', 'BPL Certificate', 'Bank Passbook'],
    category: 'Social',
    community: 'Normal',
    officialUrl: 'https://www.pmuy.gov.in/',
    image: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?q=80&w=800&auto=format&fit=crop',
    aiVersion: 'Mitra Core v1.0'
  },
  {
    id: 'pm-svanidhi',
    mitraId: 'MITRA-STATIC-SVANIDHI-009',
    name: 'PM SVANidhi',
    hindiName: 'पीएम स्वनिधि',
    description: 'Micro-credit facility for street vendors to restart their livelihoods.',
    hindiDescription: 'रेहड़ी-पटरी वालों को अपनी आजीविका फिर से शुरू करने के लिए सूक्ष्म ऋण सुविधा।',
    eligibility: ['Street vendors', 'Urban or semi-urban areas'],
    benefits: ['Collateral-free loan up to ₹50,000', 'Interest subsidy'],
    documents: ['Vending Certificate', 'Aadhar Card', 'Bank Passbook'],
    category: 'Finance',
    community: 'Jobs',
    officialUrl: 'https://pmsvanidhi.mohua.gov.in/',
    image: 'https://images.unsplash.com/photo-1607619056574-7b8d304f3c6f?q=80&w=800&auto=format&fit=crop',
    aiVersion: 'Mitra Core v1.0'
  },
  {
    id: 'pmkvy',
    mitraId: 'MITRA-STATIC-PMKVY-011',
    name: 'PM Kaushal Vikas Yojana',
    hindiName: 'प्रधानमंत्री कौशल विकास योजना',
    description: 'Skill certification scheme to enable Indian youth to take up industry-relevant skill training.',
    hindiDescription: 'भारतीय युवाओं को उद्योग-प्रासंगिक कौशल प्रशिक्षण लेने में सक्षम बनाने के लिए कौशल प्रमाणन योजना।',
    eligibility: ['Indian youth aged 18-35', 'Unemployed or school/college dropouts'],
    benefits: ['Free skill training', 'Certification and placement support'],
    documents: ['Aadhar Card', 'Bank Account', 'Educational Certificates'],
    category: 'Employment',
    community: 'Jobs',
    officialUrl: 'https://www.pmkvyofficial.org/',
    image: 'https://images.unsplash.com/photo-1521737711867-e3b97375f902?q=80&w=800&auto=format&fit=crop',
    aiVersion: 'Mitra Core v1.0'
  },
  {
    id: 'ncs-portal',
    mitraId: 'MITRA-STATIC-NCS-012',
    name: 'National Career Service',
    hindiName: 'राष्ट्रीय करियर सेवा (NCS)',
    description: 'Portal providing a wide range of employment and career-related services to the citizens.',
    hindiDescription: 'नागरिकों को रोजगार और करियर संबंधी सेवाओं की एक विस्तृत श्रृंखला प्रदान करने वाला पोर्टल।',
    eligibility: ['Job seekers', 'Employers', 'Counselors'],
    benefits: ['Free job match-making', 'Career counseling', 'Skill training info'],
    documents: ['Aadhar Card', 'Resume', 'Educational Details'],
    category: 'Employment',
    community: 'Jobs',
    officialUrl: 'https://www.ncs.gov.in/',
    image: 'https://images.unsplash.com/photo-1586281380349-632531db7ed4?q=80&w=800&auto=format&fit=crop',
    aiVersion: 'Mitra Core v1.0'
  },
  {
    id: 'mgnrega',
    mitraId: 'MITRA-STATIC-MGNREGA-010',
    name: 'MGNREGA (Work from Village)',
    hindiName: 'मनरेगा (ग्रामीण रोजगार गारंटी)',
    description: 'Guarantees 100 days of wage employment in a financial year to every rural household.',
    hindiDescription: 'प्रत्येक ग्रामीण परिवार को एक वित्तीय वर्ष में 100 दिनों के मजदूरी रोजगार की गारंटी।',
    eligibility: ['Rural households', 'Adult members willing to do unskilled manual work'],
    benefits: ['Guaranteed employment', 'Unemployment allowance if work not provided'],
    documents: ['Job Card', 'Aadhar Card', 'Bank Passbook'],
    category: 'Employment',
    community: 'Normal',
    officialUrl: 'https://nrega.nic.in/',
    image: 'https://images.unsplash.com/photo-1589923188900-85dae523342b?q=80&w=800&auto=format&fit=crop',
    aiVersion: 'Mitra Core v1.0'
  },
  {
    id: 'nsp-post-matric',
    mitraId: 'MITRA-STATIC-NSP-013',
    name: 'NSP Post-Matric Scholarship Scheme',
    hindiName: 'NSP पोस्ट-मैट्रिक स्कॉलरशिप योजना',
    description: 'Financial assistance for minority and underprivileged students pursuing post-matriculation courses.',
    hindiDescription: 'पोस्ट-मैट्रिकुलेशन पाठ्यक्रमों को आगे बढ़ाने वाले अल्पसंख्यक और वंचित छात्रों के लिए वित्तीय सहायता।',
    eligibility: ['Family income below ₹2.0 Lakhs', 'Passed preceding exam', 'Belongs to minority/SC/ST/OBC category'],
    benefits: ['₹1,200 per month hosteller allowance', '₹550 per month day scholar allowance', '100% Course fees reimbursement up to limits'],
    documents: ['Aadhar Card', 'Previous Class Marksheet', 'Income Certificate', 'Community Certificate', 'Bank Passbook'],
    category: 'Education',
    community: 'Student',
    state: 'National',
    officialUrl: 'https://scholarships.gov.in/',
    image: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?q=80&w=800&auto=format&fit=crop',
    aiVersion: 'Mitra Core v1.2',
    deadline: Date.now() + 45 * 24 * 60 * 60 * 1000, // 45 days left (OPEN)
    lastUpdate: Date.now() - 15000,
    ageLimit: 'Must be under 30 years',
    gpaRequirement: 'Minimum 50% marks in the previous final examination',
    applicationMode: 'Online',
    monthlyAmount: '₹1,200 per month (hosteller) / ₹550 per month (day scholar)',
    nextCycleExpected: 'Expected Opens July 2027',
    lastDeadline: '31 Oct 2026',
    opening: '1 Jun 2026'
  },
  {
    id: 'pm-yashasvi',
    mitraId: 'MITRA-STATIC-YASHASVI-014',
    name: 'PM YASHASVI Scholarship',
    hindiName: 'पीएम यशस्वी छात्रवृत्ति योजना',
    description: 'Highly competitive national scholarship for OBC, EBC, and DNT students in top-class schools.',
    hindiDescription: 'शीर्ष श्रेणी के स्कूलों में ओबीसी, ईबीसी और डीएनटी छात्रों के लिए अत्यधिक प्रतिस्पर्धी राष्ट्रीय छात्रवृत्ति।',
    eligibility: ['OBC/EBC/DNT categories studying in Class 9 or 11', 'Family income below ₹2.5 Lakhs'],
    benefits: ['Full school fee reimbursement', '₹10,400 per month standard grant (up to ₹1,25,000 per year)', 'Free books and notebook allowance'],
    documents: ['Aadhar Card', 'Income Certificate', 'Category Certificate', 'School Identity Card', 'Class 8th or 10th Marksheet'],
    category: 'Education',
    community: 'Student',
    state: 'National',
    officialUrl: 'https://yet.nta.ac.in/',
    image: 'https://images.unsplash.com/photo-1427504494785-3a9ca7044f45?q=80&w=800&auto=format&fit=crop',
    aiVersion: 'Mitra Core v1.2',
    deadline: Date.now() + 5 * 24 * 60 * 60 * 1000, // 5 days left (OPEN - HIGH URGENCY)
    lastUpdate: Date.now() - 2000,
    ageLimit: 'Must be between 15 and 19 years old',
    gpaRequirement: 'Minimum 60% marks in Class 8th or Class 10th exams',
    applicationMode: 'Online',
    monthlyAmount: '₹10,400 per month (up to ₹1,25,000 per year)',
    nextCycleExpected: 'Expected Opens July 2027',
    lastDeadline: '5 Sep 2026',
    opening: '1 Jul 2026'
  },
  {
    id: 'cbse-single-girl',
    mitraId: 'MITRA-STATIC-CBSE-015',
    name: 'CBSE Single Girl Child Scholarship',
    hindiName: 'CBSE एकल बालिका छात्रवृत्ति योजना',
    description: 'Scholarship to meritorious single girl children who are the only child of their parents.',
    hindiDescription: 'उन मेधावी एकल बालिकाओं को छात्रवृत्ति जो अपने माता-पिता की एकमात्र संतान हैं।',
    eligibility: ['Single girl child of parents', 'Currently studying in CBSE Class 11 or 12', 'Tuition fee less than ₹1,500/month'],
    benefits: ['₹500 per month standard grant', 'Exemption from school tuition fees', 'Direct Bank Transfer of award money'],
    documents: ['CBSE Class 10th Marksheet', 'Affidavit regarding Single Girl Child status', 'School Principal Attestation form', 'Aadhar Card'],
    category: 'Education',
    community: 'Student',
    state: 'National',
    officialUrl: 'https://www.cbse.gov.in/',
    image: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?q=80&w=800&auto=format&fit=crop',
    aiVersion: 'Mitra Core v1.2',
    deadline: Date.now() - 10 * 24 * 60 * 60 * 1000, // 10 days ago (CLOSED / DEADLINE PASSED)
    lastUpdate: Date.now() - 100000,
    ageLimit: 'Must be under 18 years old',
    gpaRequirement: 'Minimum 60% aggregate marks in Class 10th CBSE board exam',
    applicationMode: 'Online',
    monthlyAmount: '₹500 per month (fixed academic stipend)',
    nextCycleExpected: 'Expected Opens September 2026',
    lastDeadline: '10 Dec 2025',
    opening: '1 Sep 2025'
  }
];

export const STATES = [
  "Andhra Pradesh", "Arunachal Pradesh", "Assam", "Bihar", "Chhattisgarh", 
  "Goa", "Gujarat", "Haryana", "Himachal Pradesh", "Jharkhand", "Karnataka", 
  "Kerala", "Madhya Pradesh", "Maharashtra", "Manipur", "Meghalaya", "Mizoram", 
  "Nagaland", "Odisha", "Punjab", "Rajasthan", "Sikkim", "Tamil Nadu", "Telangana", 
  "Tripura", "Uttar Pradesh", "Uttarakhand", "West Bengal", "Delhi"
];
